version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5257:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__db=Server=db;Database=AsuitAqaarDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    depends_on:
      - db
    networks:
      - aqaraat-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - aqaraat-network

volumes:
  sqlserver_data:

networks:
  aqaraat-network:
    driver: bridge 